name: Dead Links (Cron)

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 1"

permissions:
  issues: write

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir . --verbose --no-progress 'README.md'

      - name: Create Issue From File
        if: failure()
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
