name: Dead Links (Fail Fast)

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  check-links-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir . --no-progress 'README.md'

      - name: Broken Link Detected
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('./lychee/out.md', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
